### ISSUE TITLE
Initial Setup Guide

### ISSUE THREAD

**Issue by Shadoghast** [Reaver01/Hex-Assist#1]
I'm feeling pretty dense, because I'd love to use this module as a key part of my West Marches campaign, but from the readme provided, I have no idea how to set it up for actual use.  Are there any plans to do a walkthru video on youtube or some more details on using the grids, tokens, etc?  I'd really appreciate it.

**Comment by Reaver01** [comment]
I have made a wiki page with world setup info. Please let me know if this is sufficient!
https://github.com/Reaver01/Hex-Assist/wiki/Initial-World-Setup

**Comment by Reaver01** [comment]
I don't do videos, so I hope that document of gifs and text explanations will help you out.

**Comment by Shadoghast** [comment]
Yep!  Exactly what I was looking for.  Thank you!!
