### ISSUE TITLE
Macros aren't being included with installation.

### ISSUE THREAD

**Issue by Firgof** [Reaver01/Hex-Assist#2]
As title states, the macros that are intended to be distributed with the project aren't importable on my client under the Macro section of the Compendium Packs.

**Comment by Reaver01** [comment]
So I just removed and re-added the module in my test environment to see if I could replicate. The compendium is definitely still there importing into Foundry version 0.7.0. Have you made sure to activate the module?

**Comment by Firgof** [comment]
I'm on Foundry v0.6.5 (latest on Stable) with Furnace v2.2. Module is activated for the World in question, version for HCA is 0.5.2.

Macros not shown in Compendium Packs: https://imgur.com/2UHY3Mv
Module shown as Active under Module Management: https://imgur.com/AUBPuhV

**Comment by Firgof** [comment]
Double checked the module folder itself and I do see the JS and DB files that are missing from the compendium packs section.
/packs/hex-assist-macros.db
/macros/hex-crawler.js
/macros/reset-hidden.js

Files don't appear corrupt when I open them up in Atom to check them out.

**Comment by Reaver01** [comment]
I am still not able to reproduce this issue on my machine or other machines I have tried this on.
