### ISSUE TITLE
After setup, still getting "The current grid is not a Hex Grid!" 

### ISSUE THREAD

**Issue by Rawrly85** [Reaver01/Hex-Assist#3]
After doing the setup, I can't seem to get this module to work. 
Here is my setup, note that the Fog of War tile token is tile_0.png but I'm not sure how it's determining the path to this token?   
![image](https://user-images.githubusercontent.com/53245027/94769203-56a2f600-0366-11eb-9ea1-77b1fc20a329.png)

Here is the layout on page
![image](https://user-images.githubusercontent.com/53245027/94769363-b4374280-0366-11eb-8b05-47eeb47f100c.png)

Foundry Version: 0.6.6
Hex Assist Version: 0.5.2

**Comment by Reaver01** [comment]
Please provide your fvtt version number, hex assist version number, and export the scene json and attach.

**Comment by Rawrly85** [comment]
Sorry, I updated with the information. Had to make the JSON into a text file in order to upload. 
[fvtt-player-map.txt](https://github.com/Reaver01/Hex-Assist/files/5309539/fvtt-player-map.txt)

**Comment by Reaver01** [comment]
Can you post a screenshot of the scene config?

**Comment by Reaver01** [comment]
According to the json you provided the grid type is 5. Unless something has changed 2 and 4 are the only ones that are hex.

**Comment by Rawrly85** [comment]
I'm not sure what 2/4 related to but I'm guessing it's an index into the options on the Grid Type. 5 is Hexagonal Columns: Even, so I'm assuming you only support Odd? From the read me file it seems like you mention only the support column, so I assumed odd was supported but maybe the list has changed order and thus it should now be 4/5 rather than 2/4?
[
<img width="744" alt="Screen Shot 2020-10-01 at 10 46 01 AM" src="https://user-images.githubusercontent.com/53245027/94844602-5856d300-03d3-11eb-8a73-9f44f21ff0f8.png">
](url)

**Comment by Reaver01** [comment]
Fixed in 0.5.3. Please update and verify
