### ISSUE TITLE
Measurement tool broken

### ISSUE THREAD

**Issue by Rinzlers** [Reaver01/Hex-Assist#4]
This module seems to break the default measurement tool (holding left ctrl while on basic controls).  Hexes light up, but there is no totaled distance displayed.

**Comment by Reaver01** [comment]
Not sure how this module could even break the measurement tool as the module doesn't do anything with measurements. I can measure with left ctrl in my own game using the Hex-Assist module with no issues. Can you please disable only Hex-Assist and confirm if the distance magically comes back?

**Comment by Rinzlers** [comment]
![disabled](https://user-images.githubusercontent.com/31813724/97723069-999cda00-1a88-11eb-94c9-608dd566bf5e.png)
![Enabled](https://user-images.githubusercontent.com/31813724/97723075-9b669d80-1a88-11eb-81e1-974ca6fe92f6.png)

**Comment by Rinzlers** [comment]
It is a strange one.  I am trying to set up this map to use your module now.

**Comment by Reaver01** [comment]
Can you hit f12 and go to the console and see if there are any errors?

**Comment by Rinzlers** [comment]
Sure thing
![image](https://user-images.githubusercontent.com/31813724/97724959-d36ee000-1a8a-11eb-8917-62ed41801fc2.png)

**Comment by Rinzlers** [comment]
I figured it out!
It has nothing to do with your module.

**Comment by Reaver01** [comment]
Oh? What ended up being the issue?

**Comment by Rinzlers** [comment]
I can replicate it now.  It is when you do the following:
Configure scene.
Grid configuration tool
Commit Changes Button (No changes are required)
= Broken Measurement

**Comment by Rinzlers** [comment]
f5 repairs the issue

**Comment by Reaver01** [comment]
Nice. Might want to see if it's submitted in the foundry tracker: https://gitlab.com/foundrynet/foundryvtt/-/issues?scope=all&utf8=%E2%9C%93&state=opened

**Comment by Rinzlers** [comment]
Sorry to bug you sir
I will report this if it hasn't been already in the proper spot.
